const express = require('express');
const router = express.Router();
const { createUser, findAllUsers, findUser, deleteUser, updateUser } = require('../controllers/users');
const { createPost, findAllPosts } = require('../controllers/posts');
router.post('/createUser', createUser);
router.get('/getAllUsers', findAllUsers);
router.get('/getUser/:id', findUser);
router.post('/createPost', createPost);
router.get('/getAllPosts', findAllPosts);
router.post('/deleteUser/:id', deleteUser);
router.post('/updateUser/:id', updateUser);
module.exports = router;